#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="elTrebol")]
	public partial class ElTrebolDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAvatar(Avatar instance);
    partial void UpdateAvatar(Avatar instance);
    partial void DeleteAvatar(Avatar instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertComentario(Comentario instance);
    partial void UpdateComentario(Comentario instance);
    partial void DeleteComentario(Comentario instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertFormaPago(FormaPago instance);
    partial void UpdateFormaPago(FormaPago instance);
    partial void DeleteFormaPago(FormaPago instance);
    partial void InsertFoto(Foto instance);
    partial void UpdateFoto(Foto instance);
    partial void DeleteFoto(Foto instance);
    partial void InsertLocalidad(Localidad instance);
    partial void UpdateLocalidad(Localidad instance);
    partial void DeleteLocalidad(Localidad instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertProvincia(Provincia instance);
    partial void UpdateProvincia(Provincia instance);
    partial void DeleteProvincia(Provincia instance);
    partial void InsertPublicacion(Publicacion instance);
    partial void UpdatePublicacion(Publicacion instance);
    partial void DeletePublicacion(Publicacion instance);
    partial void InsertRules(Rules instance);
    partial void UpdateRules(Rules instance);
    partial void DeleteRules(Rules instance);
    partial void InsertTipoNegocio(TipoNegocio instance);
    partial void UpdateTipoNegocio(TipoNegocio instance);
    partial void DeleteTipoNegocio(TipoNegocio instance);
    #endregion
		
		public ElTrebolDBDataContext() : 
				base(global::AppTP.Properties.Settings.Default.elTrebolConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ElTrebolDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElTrebolDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElTrebolDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElTrebolDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Avatar> Avatar
		{
			get
			{
				return this.GetTable<Avatar>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentario
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estado
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<FormaPago> FormaPago
		{
			get
			{
				return this.GetTable<FormaPago>();
			}
		}
		
		public System.Data.Linq.Table<Foto> Foto
		{
			get
			{
				return this.GetTable<Foto>();
			}
		}
		
		public System.Data.Linq.Table<Localidad> Localidad
		{
			get
			{
				return this.GetTable<Localidad>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Provincia> Provincia
		{
			get
			{
				return this.GetTable<Provincia>();
			}
		}
		
		public System.Data.Linq.Table<Publicacion> Publicacion
		{
			get
			{
				return this.GetTable<Publicacion>();
			}
		}
		
		public System.Data.Linq.Table<Rules> Rules
		{
			get
			{
				return this.GetTable<Rules>();
			}
		}
		
		public System.Data.Linq.Table<TipoNegocio> TipoNegocio
		{
			get
			{
				return this.GetTable<TipoNegocio>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.paginacion_antiguosPrimero")]
		public ISingleResult<paginacion_antiguosPrimeroResult> paginacion_antiguosPrimero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(20,2)")] System.Nullable<decimal> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), indice, cantidad, total);
			total = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<paginacion_antiguosPrimeroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.paginacion_nuevosPrimero")]
		public ISingleResult<paginacion_nuevosPrimeroResult> paginacion_nuevosPrimero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> indice, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(20,2)")] System.Nullable<decimal> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), indice, cantidad, total);
			total = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<paginacion_nuevosPrimeroResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avatar")]
	public partial class Avatar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_avatar;
		
		private string _avatar1;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_avatarChanging(int value);
    partial void Onid_avatarChanged();
    partial void Onavatar1Changing(string value);
    partial void Onavatar1Changed();
    #endregion
		
		public Avatar()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_avatar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_avatar
		{
			get
			{
				return this._id_avatar;
			}
			set
			{
				if ((this._id_avatar != value))
				{
					this.Onid_avatarChanging(value);
					this.SendPropertyChanging();
					this._id_avatar = value;
					this.SendPropertyChanged("id_avatar");
					this.Onid_avatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="avatar", Storage="_avatar1", DbType="VarChar(300)")]
		public string avatar1
		{
			get
			{
				return this._avatar1;
			}
			set
			{
				if ((this._avatar1 != value))
				{
					this.Onavatar1Changing(value);
					this.SendPropertyChanging();
					this._avatar1 = value;
					this.SendPropertyChanged("avatar1");
					this.Onavatar1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avatar_Usuario", Storage="_Usuario", ThisKey="id_avatar", OtherKey="id_avatar")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Avatar = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Avatar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _username;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _mail;
		
		private string _pass;
		
		private long _telefono;
		
		private System.Nullable<int> _id_avatar;
		
		private int _id_rules;
		
		private System.Nullable<int> _id_foto;
		
		private EntitySet<Comentario> _Comentario;
		
		private EntityRef<Avatar> _Avatar;
		
		private EntityRef<Foto> _Foto;
		
		private EntityRef<Rules> _Rules;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OntelefonoChanging(long value);
    partial void OntelefonoChanged();
    partial void Onid_avatarChanging(System.Nullable<int> value);
    partial void Onid_avatarChanged();
    partial void Onid_rulesChanging(int value);
    partial void Onid_rulesChanged();
    partial void Onid_fotoChanging(System.Nullable<int> value);
    partial void Onid_fotoChanged();
    #endregion
		
		public Usuario()
		{
			this._Comentario = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentario), new Action<Comentario>(this.detach_Comentario));
			this._Avatar = default(EntityRef<Avatar>);
			this._Foto = default(EntityRef<Foto>);
			this._Rules = default(EntityRef<Rules>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt NOT NULL")]
		public long telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_avatar", DbType="Int")]
		public System.Nullable<int> id_avatar
		{
			get
			{
				return this._id_avatar;
			}
			set
			{
				if ((this._id_avatar != value))
				{
					if (this._Avatar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_avatarChanging(value);
					this.SendPropertyChanging();
					this._id_avatar = value;
					this.SendPropertyChanged("id_avatar");
					this.Onid_avatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rules", DbType="Int NOT NULL")]
		public int id_rules
		{
			get
			{
				return this._id_rules;
			}
			set
			{
				if ((this._id_rules != value))
				{
					if (this._Rules.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rulesChanging(value);
					this.SendPropertyChanging();
					this._id_rules = value;
					this.SendPropertyChanged("id_rules");
					this.Onid_rulesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_foto", DbType="Int")]
		public System.Nullable<int> id_foto
		{
			get
			{
				return this._id_foto;
			}
			set
			{
				if ((this._id_foto != value))
				{
					if (this._Foto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fotoChanging(value);
					this.SendPropertyChanging();
					this._id_foto = value;
					this.SendPropertyChanged("id_foto");
					this.Onid_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Comentario", Storage="_Comentario", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Comentario> Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				this._Comentario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avatar_Usuario", Storage="_Avatar", ThisKey="id_avatar", OtherKey="id_avatar", IsForeignKey=true)]
		public Avatar Avatar
		{
			get
			{
				return this._Avatar.Entity;
			}
			set
			{
				Avatar previousValue = this._Avatar.Entity;
				if (((previousValue != value) 
							|| (this._Avatar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avatar.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Avatar.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._id_avatar = value.id_avatar;
					}
					else
					{
						this._id_avatar = default(Nullable<int>);
					}
					this.SendPropertyChanged("Avatar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Foto_Usuario", Storage="_Foto", ThisKey="id_foto", OtherKey="id_foto", IsForeignKey=true)]
		public Foto Foto
		{
			get
			{
				return this._Foto.Entity;
			}
			set
			{
				Foto previousValue = this._Foto.Entity;
				if (((previousValue != value) 
							|| (this._Foto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Foto.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Foto.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._id_foto = value.id_foto;
					}
					else
					{
						this._id_foto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Foto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rules_Usuario", Storage="_Rules", ThisKey="id_rules", OtherKey="id_rules", IsForeignKey=true)]
		public Rules Rules
		{
			get
			{
				return this._Rules.Entity;
			}
			set
			{
				Rules previousValue = this._Rules.Entity;
				if (((previousValue != value) 
							|| (this._Rules.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rules.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Rules.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._id_rules = value.id_rules;
					}
					else
					{
						this._id_rules = default(int);
					}
					this.SendPropertyChanged("Rules");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentario")]
	public partial class Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_comentario;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _mail;
		
		private long _telefono;
		
		private long _celular;
		
		private System.DateTime _fecha_pregunta;
		
		private string _comentario1;
		
		private System.Nullable<System.DateTime> _fecha_respuesta;
		
		private string _respuesta;
		
		private System.Nullable<int> _id_publicacion;
		
		private System.Nullable<int> _id_usuario;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Publicacion> _Publicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_comentarioChanging(int value);
    partial void Onid_comentarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OntelefonoChanging(long value);
    partial void OntelefonoChanged();
    partial void OncelularChanging(long value);
    partial void OncelularChanged();
    partial void Onfecha_preguntaChanging(System.DateTime value);
    partial void Onfecha_preguntaChanged();
    partial void Oncomentario1Changing(string value);
    partial void Oncomentario1Changed();
    partial void Onfecha_respuestaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_respuestaChanged();
    partial void OnrespuestaChanging(string value);
    partial void OnrespuestaChanged();
    partial void Onid_publicacionChanging(System.Nullable<int> value);
    partial void Onid_publicacionChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    #endregion
		
		public Comentario()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._Publicacion = default(EntityRef<Publicacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_comentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_comentario
		{
			get
			{
				return this._id_comentario;
			}
			set
			{
				if ((this._id_comentario != value))
				{
					this.Onid_comentarioChanging(value);
					this.SendPropertyChanging();
					this._id_comentario = value;
					this.SendPropertyChanged("id_comentario");
					this.Onid_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt NOT NULL")]
		public long telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="BigInt NOT NULL")]
		public long celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_pregunta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_pregunta
		{
			get
			{
				return this._fecha_pregunta;
			}
			set
			{
				if ((this._fecha_pregunta != value))
				{
					this.Onfecha_preguntaChanging(value);
					this.SendPropertyChanging();
					this._fecha_pregunta = value;
					this.SendPropertyChanged("fecha_pregunta");
					this.Onfecha_preguntaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="comentario", Storage="_comentario1", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string comentario1
		{
			get
			{
				return this._comentario1;
			}
			set
			{
				if ((this._comentario1 != value))
				{
					this.Oncomentario1Changing(value);
					this.SendPropertyChanging();
					this._comentario1 = value;
					this.SendPropertyChanged("comentario1");
					this.Oncomentario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_respuesta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_respuesta
		{
			get
			{
				return this._fecha_respuesta;
			}
			set
			{
				if ((this._fecha_respuesta != value))
				{
					this.Onfecha_respuestaChanging(value);
					this.SendPropertyChanging();
					this._fecha_respuesta = value;
					this.SendPropertyChanged("fecha_respuesta");
					this.Onfecha_respuestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_respuesta", DbType="VarChar(500)")]
		public string respuesta
		{
			get
			{
				return this._respuesta;
			}
			set
			{
				if ((this._respuesta != value))
				{
					this.OnrespuestaChanging(value);
					this.SendPropertyChanging();
					this._respuesta = value;
					this.SendPropertyChanged("respuesta");
					this.OnrespuestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", DbType="Int")]
		public System.Nullable<int> id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					if (this._Publicacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_publicacionChanging(value);
					this.SendPropertyChanging();
					this._id_publicacion = value;
					this.SendPropertyChanged("id_publicacion");
					this.Onid_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Comentario", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Comentario.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Comentario.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Comentario", Storage="_Publicacion", ThisKey="id_publicacion", OtherKey="id_publicacion", IsForeignKey=true)]
		public Publicacion Publicacion
		{
			get
			{
				return this._Publicacion.Entity;
			}
			set
			{
				Publicacion previousValue = this._Publicacion.Entity;
				if (((previousValue != value) 
							|| (this._Publicacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Publicacion.Entity = null;
						previousValue.Comentario.Remove(this);
					}
					this._Publicacion.Entity = value;
					if ((value != null))
					{
						value.Comentario.Add(this);
						this._id_publicacion = value.id_publicacion;
					}
					else
					{
						this._id_publicacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Publicacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _idProvincia;
		
		private string _Nombre;
		
		private EntitySet<Localidad> _Localidad;
		
		private EntityRef<Provincia> _Provincia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnidProvinciaChanging(int value);
    partial void OnidProvinciaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Departamento()
		{
			this._Localidad = new EntitySet<Localidad>(new Action<Localidad>(this.attach_Localidad), new Action<Localidad>(this.detach_Localidad));
			this._Provincia = default(EntityRef<Provincia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="Int NOT NULL")]
		public int idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					if (this._Provincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProvinciaChanging(value);
					this.SendPropertyChanging();
					this._idProvincia = value;
					this.SendPropertyChanged("idProvincia");
					this.OnidProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Localidad", Storage="_Localidad", ThisKey="ID", OtherKey="idDepartamento")]
		public EntitySet<Localidad> Localidad
		{
			get
			{
				return this._Localidad;
			}
			set
			{
				this._Localidad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Departamento", Storage="_Provincia", ThisKey="idProvincia", OtherKey="ID", IsForeignKey=true)]
		public Provincia Provincia
		{
			get
			{
				return this._Provincia.Entity;
			}
			set
			{
				Provincia previousValue = this._Provincia.Entity;
				if (((previousValue != value) 
							|| (this._Provincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincia.Entity = null;
						previousValue.Departamento.Remove(this);
					}
					this._Provincia.Entity = value;
					if ((value != null))
					{
						value.Departamento.Add(this);
						this._idProvincia = value.ID;
					}
					else
					{
						this._idProvincia = default(int);
					}
					this.SendPropertyChanged("Provincia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Localidad(Localidad entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Localidad(Localidad entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_estado;
		
		private string _estado1;
		
		private EntitySet<Publicacion> _Publicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estadoChanging(int value);
    partial void Onid_estadoChanged();
    partial void Onestado1Changing(string value);
    partial void Onestado1Changed();
    #endregion
		
		public Estado()
		{
			this._Publicacion = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacion), new Action<Publicacion>(this.detach_Publicacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					this.Onid_estadoChanging(value);
					this.SendPropertyChanging();
					this._id_estado = value;
					this.SendPropertyChanged("id_estado");
					this.Onid_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="estado", Storage="_estado1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string estado1
		{
			get
			{
				return this._estado1;
			}
			set
			{
				if ((this._estado1 != value))
				{
					this.Onestado1Changing(value);
					this.SendPropertyChanging();
					this._estado1 = value;
					this.SendPropertyChanged("estado1");
					this.Onestado1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Publicacion", Storage="_Publicacion", ThisKey="id_estado", OtherKey="id_estado")]
		public EntitySet<Publicacion> Publicacion
		{
			get
			{
				return this._Publicacion;
			}
			set
			{
				this._Publicacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormaPago")]
	public partial class FormaPago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_formaPago;
		
		private string _formaPago1;
		
		private EntitySet<Publicacion> _Publicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_formaPagoChanging(int value);
    partial void Onid_formaPagoChanged();
    partial void OnformaPago1Changing(string value);
    partial void OnformaPago1Changed();
    #endregion
		
		public FormaPago()
		{
			this._Publicacion = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacion), new Action<Publicacion>(this.detach_Publicacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_formaPago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_formaPago
		{
			get
			{
				return this._id_formaPago;
			}
			set
			{
				if ((this._id_formaPago != value))
				{
					this.Onid_formaPagoChanging(value);
					this.SendPropertyChanging();
					this._id_formaPago = value;
					this.SendPropertyChanged("id_formaPago");
					this.Onid_formaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="formaPago", Storage="_formaPago1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string formaPago1
		{
			get
			{
				return this._formaPago1;
			}
			set
			{
				if ((this._formaPago1 != value))
				{
					this.OnformaPago1Changing(value);
					this.SendPropertyChanging();
					this._formaPago1 = value;
					this.SendPropertyChanged("formaPago1");
					this.OnformaPago1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormaPago_Publicacion", Storage="_Publicacion", ThisKey="id_formaPago", OtherKey="id_formaPago")]
		public EntitySet<Publicacion> Publicacion
		{
			get
			{
				return this._Publicacion;
			}
			set
			{
				this._Publicacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.FormaPago = this;
		}
		
		private void detach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.FormaPago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Foto")]
	public partial class Foto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_foto;
		
		private string _foto1;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_fotoChanging(int value);
    partial void Onid_fotoChanged();
    partial void Onfoto1Changing(string value);
    partial void Onfoto1Changed();
    #endregion
		
		public Foto()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_foto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_foto
		{
			get
			{
				return this._id_foto;
			}
			set
			{
				if ((this._id_foto != value))
				{
					this.Onid_fotoChanging(value);
					this.SendPropertyChanging();
					this._id_foto = value;
					this.SendPropertyChanged("id_foto");
					this.Onid_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="foto", Storage="_foto1", DbType="VarChar(100)")]
		public string foto1
		{
			get
			{
				return this._foto1;
			}
			set
			{
				if ((this._foto1 != value))
				{
					this.Onfoto1Changing(value);
					this.SendPropertyChanging();
					this._foto1 = value;
					this.SendPropertyChanged("foto1");
					this.Onfoto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Foto_Usuario", Storage="_Usuario", ThisKey="id_foto", OtherKey="id_foto")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Foto = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Foto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Localidad")]
	public partial class Localidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _idDepartamento;
		
		private string _Nombre;
		
		private EntitySet<Publicacion> _Publicacion;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Localidad()
		{
			this._Publicacion = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacion), new Action<Publicacion>(this.detach_Publicacion));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Publicacion", Storage="_Publicacion", ThisKey="ID", OtherKey="id_localidad")]
		public EntitySet<Publicacion> Publicacion
		{
			get
			{
				return this._Publicacion;
			}
			set
			{
				this._Publicacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Localidad", Storage="_Departamento", ThisKey="idDepartamento", OtherKey="ID", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Localidad.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Localidad.Add(this);
						this._idDepartamento = value.ID;
					}
					else
					{
						this._idDepartamento = default(int);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Localidad = this;
		}
		
		private void detach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Localidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _nombre;
		
		private EntitySet<Publicacion> _Publicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Producto()
		{
			this._Publicacion = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacion), new Action<Publicacion>(this.detach_Publicacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Publicacion", Storage="_Publicacion", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Publicacion> Publicacion
		{
			get
			{
				return this._Publicacion;
			}
			set
			{
				this._Publicacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provincia")]
	public partial class Provincia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private EntitySet<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Provincia()
		{
			this._Departamento = new EntitySet<Departamento>(new Action<Departamento>(this.attach_Departamento), new Action<Departamento>(this.detach_Departamento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincia_Departamento", Storage="_Departamento", ThisKey="ID", OtherKey="idProvincia")]
		public EntitySet<Departamento> Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				this._Departamento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Departamento(Departamento entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = this;
		}
		
		private void detach_Departamento(Departamento entity)
		{
			this.SendPropertyChanging();
			entity.Provincia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Publicacion")]
	public partial class Publicacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_publicacion;
		
		private string _titulo;
		
		private string _fotos;
		
		private System.Nullable<decimal> _precio;
		
		private string _descripcion;
		
		private string _barrio;
		
		private System.DateTime _fecha_publicacion;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _motivo_baja;
		
		private System.Nullable<int> _votantes;
		
		private System.Nullable<decimal> _valoracion;
		
		private System.Nullable<int> _id_producto;
		
		private System.Nullable<int> _id_estado;
		
		private System.Nullable<int> _id_formaPago;
		
		private System.Nullable<int> _id_tipoNegocio;
		
		private System.Nullable<int> _id_admin;
		
		private System.Nullable<int> _id_localidad;
		
		private EntitySet<Comentario> _Comentario;
		
		private EntityRef<Estado> _Estado;
		
		private EntityRef<FormaPago> _FormaPago;
		
		private EntityRef<Localidad> _Localidad;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<TipoNegocio> _TipoNegocio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_publicacionChanging(int value);
    partial void Onid_publicacionChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OnfotosChanging(string value);
    partial void OnfotosChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnbarrioChanging(string value);
    partial void OnbarrioChanged();
    partial void Onfecha_publicacionChanging(System.DateTime value);
    partial void Onfecha_publicacionChanged();
    partial void Onfecha_bajaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_bajaChanged();
    partial void Onmotivo_bajaChanging(string value);
    partial void Onmotivo_bajaChanged();
    partial void OnvotantesChanging(System.Nullable<int> value);
    partial void OnvotantesChanged();
    partial void OnvaloracionChanging(System.Nullable<decimal> value);
    partial void OnvaloracionChanged();
    partial void Onid_productoChanging(System.Nullable<int> value);
    partial void Onid_productoChanged();
    partial void Onid_estadoChanging(System.Nullable<int> value);
    partial void Onid_estadoChanged();
    partial void Onid_formaPagoChanging(System.Nullable<int> value);
    partial void Onid_formaPagoChanged();
    partial void Onid_tipoNegocioChanging(System.Nullable<int> value);
    partial void Onid_tipoNegocioChanged();
    partial void Onid_adminChanging(System.Nullable<int> value);
    partial void Onid_adminChanged();
    partial void Onid_localidadChanging(System.Nullable<int> value);
    partial void Onid_localidadChanged();
    #endregion
		
		public Publicacion()
		{
			this._Comentario = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentario), new Action<Comentario>(this.detach_Comentario));
			this._Estado = default(EntityRef<Estado>);
			this._FormaPago = default(EntityRef<FormaPago>);
			this._Localidad = default(EntityRef<Localidad>);
			this._Producto = default(EntityRef<Producto>);
			this._TipoNegocio = default(EntityRef<TipoNegocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					this.Onid_publicacionChanging(value);
					this.SendPropertyChanging();
					this._id_publicacion = value;
					this.SendPropertyChanged("id_publicacion");
					this.Onid_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotos", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string fotos
		{
			get
			{
				return this._fotos;
			}
			set
			{
				if ((this._fotos != value))
				{
					this.OnfotosChanging(value);
					this.SendPropertyChanging();
					this._fotos = value;
					this.SendPropertyChanged("fotos");
					this.OnfotosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this.OnbarrioChanging(value);
					this.SendPropertyChanging();
					this._barrio = value;
					this.SendPropertyChanged("barrio");
					this.OnbarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_publicacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_publicacion
		{
			get
			{
				return this._fecha_publicacion;
			}
			set
			{
				if ((this._fecha_publicacion != value))
				{
					this.Onfecha_publicacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_publicacion = value;
					this.SendPropertyChanged("fecha_publicacion");
					this.Onfecha_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this.Onfecha_bajaChanging(value);
					this.SendPropertyChanging();
					this._fecha_baja = value;
					this.SendPropertyChanged("fecha_baja");
					this.Onfecha_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo_baja", DbType="VarChar(300)")]
		public string motivo_baja
		{
			get
			{
				return this._motivo_baja;
			}
			set
			{
				if ((this._motivo_baja != value))
				{
					this.Onmotivo_bajaChanging(value);
					this.SendPropertyChanging();
					this._motivo_baja = value;
					this.SendPropertyChanged("motivo_baja");
					this.Onmotivo_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_votantes", DbType="Int")]
		public System.Nullable<int> votantes
		{
			get
			{
				return this._votantes;
			}
			set
			{
				if ((this._votantes != value))
				{
					this.OnvotantesChanging(value);
					this.SendPropertyChanging();
					this._votantes = value;
					this.SendPropertyChanged("votantes");
					this.OnvotantesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this.OnvaloracionChanging(value);
					this.SendPropertyChanging();
					this._valoracion = value;
					this.SendPropertyChanged("valoracion");
					this.OnvaloracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int")]
		public System.Nullable<int> id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int")]
		public System.Nullable<int> id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estadoChanging(value);
					this.SendPropertyChanging();
					this._id_estado = value;
					this.SendPropertyChanged("id_estado");
					this.Onid_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_formaPago", DbType="Int")]
		public System.Nullable<int> id_formaPago
		{
			get
			{
				return this._id_formaPago;
			}
			set
			{
				if ((this._id_formaPago != value))
				{
					if (this._FormaPago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_formaPagoChanging(value);
					this.SendPropertyChanging();
					this._id_formaPago = value;
					this.SendPropertyChanged("id_formaPago");
					this.Onid_formaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoNegocio", DbType="Int")]
		public System.Nullable<int> id_tipoNegocio
		{
			get
			{
				return this._id_tipoNegocio;
			}
			set
			{
				if ((this._id_tipoNegocio != value))
				{
					if (this._TipoNegocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipoNegocioChanging(value);
					this.SendPropertyChanging();
					this._id_tipoNegocio = value;
					this.SendPropertyChanged("id_tipoNegocio");
					this.Onid_tipoNegocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_admin", DbType="Int")]
		public System.Nullable<int> id_admin
		{
			get
			{
				return this._id_admin;
			}
			set
			{
				if ((this._id_admin != value))
				{
					this.Onid_adminChanging(value);
					this.SendPropertyChanging();
					this._id_admin = value;
					this.SendPropertyChanged("id_admin");
					this.Onid_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_localidad", DbType="Int")]
		public System.Nullable<int> id_localidad
		{
			get
			{
				return this._id_localidad;
			}
			set
			{
				if ((this._id_localidad != value))
				{
					if (this._Localidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_localidadChanging(value);
					this.SendPropertyChanging();
					this._id_localidad = value;
					this.SendPropertyChanged("id_localidad");
					this.Onid_localidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Comentario", Storage="_Comentario", ThisKey="id_publicacion", OtherKey="id_publicacion")]
		public EntitySet<Comentario> Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				this._Comentario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Publicacion", Storage="_Estado", ThisKey="id_estado", OtherKey="id_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Publicacion.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Publicacion.Add(this);
						this._id_estado = value.id_estado;
					}
					else
					{
						this._id_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormaPago_Publicacion", Storage="_FormaPago", ThisKey="id_formaPago", OtherKey="id_formaPago", IsForeignKey=true)]
		public FormaPago FormaPago
		{
			get
			{
				return this._FormaPago.Entity;
			}
			set
			{
				FormaPago previousValue = this._FormaPago.Entity;
				if (((previousValue != value) 
							|| (this._FormaPago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormaPago.Entity = null;
						previousValue.Publicacion.Remove(this);
					}
					this._FormaPago.Entity = value;
					if ((value != null))
					{
						value.Publicacion.Add(this);
						this._id_formaPago = value.id_formaPago;
					}
					else
					{
						this._id_formaPago = default(Nullable<int>);
					}
					this.SendPropertyChanged("FormaPago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Publicacion", Storage="_Localidad", ThisKey="id_localidad", OtherKey="ID", IsForeignKey=true)]
		public Localidad Localidad
		{
			get
			{
				return this._Localidad.Entity;
			}
			set
			{
				Localidad previousValue = this._Localidad.Entity;
				if (((previousValue != value) 
							|| (this._Localidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Localidad.Entity = null;
						previousValue.Publicacion.Remove(this);
					}
					this._Localidad.Entity = value;
					if ((value != null))
					{
						value.Publicacion.Add(this);
						this._id_localidad = value.ID;
					}
					else
					{
						this._id_localidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("Localidad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Publicacion", Storage="_Producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Publicacion.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Publicacion.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoNegocio_Publicacion", Storage="_TipoNegocio", ThisKey="id_tipoNegocio", OtherKey="id_tipoNegocio", IsForeignKey=true)]
		public TipoNegocio TipoNegocio
		{
			get
			{
				return this._TipoNegocio.Entity;
			}
			set
			{
				TipoNegocio previousValue = this._TipoNegocio.Entity;
				if (((previousValue != value) 
							|| (this._TipoNegocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoNegocio.Entity = null;
						previousValue.Publicacion.Remove(this);
					}
					this._TipoNegocio.Entity = value;
					if ((value != null))
					{
						value.Publicacion.Add(this);
						this._id_tipoNegocio = value.id_tipoNegocio;
					}
					else
					{
						this._id_tipoNegocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("TipoNegocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = this;
		}
		
		private void detach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rules")]
	public partial class Rules : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rules;
		
		private string _nombre;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rulesChanging(int value);
    partial void Onid_rulesChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Rules()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rules", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rules
		{
			get
			{
				return this._id_rules;
			}
			set
			{
				if ((this._id_rules != value))
				{
					this.Onid_rulesChanging(value);
					this.SendPropertyChanging();
					this._id_rules = value;
					this.SendPropertyChanged("id_rules");
					this.Onid_rulesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rules_Usuario", Storage="_Usuario", ThisKey="id_rules", OtherKey="id_rules")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rules = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Rules = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoNegocio")]
	public partial class TipoNegocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipoNegocio;
		
		private string _tipo;
		
		private EntitySet<Publicacion> _Publicacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoNegocioChanging(int value);
    partial void Onid_tipoNegocioChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public TipoNegocio()
		{
			this._Publicacion = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacion), new Action<Publicacion>(this.detach_Publicacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoNegocio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipoNegocio
		{
			get
			{
				return this._id_tipoNegocio;
			}
			set
			{
				if ((this._id_tipoNegocio != value))
				{
					this.Onid_tipoNegocioChanging(value);
					this.SendPropertyChanging();
					this._id_tipoNegocio = value;
					this.SendPropertyChanged("id_tipoNegocio");
					this.Onid_tipoNegocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoNegocio_Publicacion", Storage="_Publicacion", ThisKey="id_tipoNegocio", OtherKey="id_tipoNegocio")]
		public EntitySet<Publicacion> Publicacion
		{
			get
			{
				return this._Publicacion;
			}
			set
			{
				this._Publicacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoNegocio = this;
		}
		
		private void detach_Publicacion(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoNegocio = null;
		}
	}
	
	public partial class paginacion_antiguosPrimeroResult
	{
		
		private System.Nullable<long> _idFilas;
		
		private int _id_publicacion;
		
		private string _titulo;
		
		private string _fotos;
		
		private System.Nullable<decimal> _precio;
		
		private string _descripcion;
		
		private string _barrio;
		
		private System.DateTime _fecha_publicacion;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _motivo_baja;
		
		private System.Nullable<int> _votantes;
		
		private System.Nullable<decimal> _valoracion;
		
		private System.Nullable<int> _id_producto;
		
		private System.Nullable<int> _id_estado;
		
		private System.Nullable<int> _id_formaPago;
		
		private System.Nullable<int> _id_tipoNegocio;
		
		private System.Nullable<int> _id_admin;
		
		private System.Nullable<int> _id_localidad;
		
		public paginacion_antiguosPrimeroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFilas", DbType="BigInt")]
		public System.Nullable<long> idFilas
		{
			get
			{
				return this._idFilas;
			}
			set
			{
				if ((this._idFilas != value))
				{
					this._idFilas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", DbType="Int NOT NULL")]
		public int id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					this._id_publicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotos", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string fotos
		{
			get
			{
				return this._fotos;
			}
			set
			{
				if ((this._fotos != value))
				{
					this._fotos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this._barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_publicacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_publicacion
		{
			get
			{
				return this._fecha_publicacion;
			}
			set
			{
				if ((this._fecha_publicacion != value))
				{
					this._fecha_publicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this._fecha_baja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo_baja", DbType="VarChar(300)")]
		public string motivo_baja
		{
			get
			{
				return this._motivo_baja;
			}
			set
			{
				if ((this._motivo_baja != value))
				{
					this._motivo_baja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_votantes", DbType="Int")]
		public System.Nullable<int> votantes
		{
			get
			{
				return this._votantes;
			}
			set
			{
				if ((this._votantes != value))
				{
					this._votantes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this._valoracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int")]
		public System.Nullable<int> id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int")]
		public System.Nullable<int> id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					this._id_estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_formaPago", DbType="Int")]
		public System.Nullable<int> id_formaPago
		{
			get
			{
				return this._id_formaPago;
			}
			set
			{
				if ((this._id_formaPago != value))
				{
					this._id_formaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoNegocio", DbType="Int")]
		public System.Nullable<int> id_tipoNegocio
		{
			get
			{
				return this._id_tipoNegocio;
			}
			set
			{
				if ((this._id_tipoNegocio != value))
				{
					this._id_tipoNegocio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_admin", DbType="Int")]
		public System.Nullable<int> id_admin
		{
			get
			{
				return this._id_admin;
			}
			set
			{
				if ((this._id_admin != value))
				{
					this._id_admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_localidad", DbType="Int")]
		public System.Nullable<int> id_localidad
		{
			get
			{
				return this._id_localidad;
			}
			set
			{
				if ((this._id_localidad != value))
				{
					this._id_localidad = value;
				}
			}
		}
	}
	
	public partial class paginacion_nuevosPrimeroResult
	{
		
		private System.Nullable<long> _idFilas;
		
		private int _id_publicacion;
		
		private string _titulo;
		
		private string _fotos;
		
		private System.Nullable<decimal> _precio;
		
		private string _descripcion;
		
		private string _barrio;
		
		private System.DateTime _fecha_publicacion;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _motivo_baja;
		
		private System.Nullable<int> _votantes;
		
		private System.Nullable<decimal> _valoracion;
		
		private System.Nullable<int> _id_producto;
		
		private System.Nullable<int> _id_estado;
		
		private System.Nullable<int> _id_formaPago;
		
		private System.Nullable<int> _id_tipoNegocio;
		
		private System.Nullable<int> _id_admin;
		
		private System.Nullable<int> _id_localidad;
		
		public paginacion_nuevosPrimeroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFilas", DbType="BigInt")]
		public System.Nullable<long> idFilas
		{
			get
			{
				return this._idFilas;
			}
			set
			{
				if ((this._idFilas != value))
				{
					this._idFilas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", DbType="Int NOT NULL")]
		public int id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					this._id_publicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotos", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string fotos
		{
			get
			{
				return this._fotos;
			}
			set
			{
				if ((this._fotos != value))
				{
					this._fotos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this._barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_publicacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_publicacion
		{
			get
			{
				return this._fecha_publicacion;
			}
			set
			{
				if ((this._fecha_publicacion != value))
				{
					this._fecha_publicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this._fecha_baja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo_baja", DbType="VarChar(300)")]
		public string motivo_baja
		{
			get
			{
				return this._motivo_baja;
			}
			set
			{
				if ((this._motivo_baja != value))
				{
					this._motivo_baja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_votantes", DbType="Int")]
		public System.Nullable<int> votantes
		{
			get
			{
				return this._votantes;
			}
			set
			{
				if ((this._votantes != value))
				{
					this._votantes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this._valoracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int")]
		public System.Nullable<int> id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int")]
		public System.Nullable<int> id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					this._id_estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_formaPago", DbType="Int")]
		public System.Nullable<int> id_formaPago
		{
			get
			{
				return this._id_formaPago;
			}
			set
			{
				if ((this._id_formaPago != value))
				{
					this._id_formaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoNegocio", DbType="Int")]
		public System.Nullable<int> id_tipoNegocio
		{
			get
			{
				return this._id_tipoNegocio;
			}
			set
			{
				if ((this._id_tipoNegocio != value))
				{
					this._id_tipoNegocio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_admin", DbType="Int")]
		public System.Nullable<int> id_admin
		{
			get
			{
				return this._id_admin;
			}
			set
			{
				if ((this._id_admin != value))
				{
					this._id_admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_localidad", DbType="Int")]
		public System.Nullable<int> id_localidad
		{
			get
			{
				return this._id_localidad;
			}
			set
			{
				if ((this._id_localidad != value))
				{
					this._id_localidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
